[versions]
agp             = "8.3.2"
kotlin          = "1.9.24"
coreKtx         = "1.13.1"
lifecycle       = "2.8.2"
activityCompose = "1.9.0"
composeBom      = "2024.06.00"
location        = "21.3.0"
okhttp          = "4.12.0"
coroutines      = "1.8.1"

[libraries]
androidx-core-ktx            = { group = "androidx.core",                name = "core-ktx",                      version.ref = "coreKtx" }
androidx-lifecycle-runtime   = { group = "androidx.lifecycle",           name = "lifecycle-runtime-ktx",          version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle",           name = "lifecycle-viewmodel-compose",    version.ref = "lifecycle" }
androidx-activity-compose    = { group = "androidx.activity",            name = "activity-compose",               version.ref = "activityCompose" }
compose-bom                  = { group = "androidx.compose",             name = "compose-bom",                    version.ref = "composeBom" }
compose-ui                   = { group = "androidx.compose.ui",          name = "ui" }
compose-ui-tooling           = { group = "androidx.compose.ui",          name = "ui-tooling-preview" }
compose-material3            = { group = "androidx.compose.material3",   name = "material3" }
play-services-location       = { group = "com.google.android.gms",       name = "play-services-location",         version.ref = "location" }
okhttp                       = { group = "com.squareup.okhttp3",          name = "okhttp",                         version.ref = "okhttp" }
kotlinx-coroutines-android   = { group = "org.jetbrains.kotlinx",        name = "kotlinx-coroutines-android",     version.ref = "coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose      = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
